#!/usr/bin/env python
# coding: utf-8

# In[21]:

print('Ibitoye Opeyemi Isaac,', '@Highzhikk,', 'Python,' , 'Ibitoyeopeyemiisaac@gmail.com', 'Genomics')

# -*- coding: utf-8 -*-
"""HackBioikadan1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10uJLvXgYYbaVvbFBjns_jPDa9cghqnd5
"""

Name = "Ika Danjuma Mbateudi"
Email = "ikadanjuma@gmail.com"
Language = "python"
Biostack = "Drug development"
Slack_username = "@ikadan"
print('Ika Danjuma Mbateudi,', '@ikadan,', 'Python,' , 'ikadanjuma@gmail.com', 'Drugs development')
# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R70BYynqLJtr48NLscdnay5CCky3rTGN
"""

Name = "Shahana Malik"
Email-address = "shanimalik@aup.edu.pk"
Language = "Python"
Biostack = "Genomics"
Slack_username = "@shani"

print("My name is Shahana Malik") 
print("My email is shanimalik@aup.edu.pk")
print("My language is python")
print("My Biostack is Genomics ")
print("My slack username is @shani")
print('adisa abdulhakeem,', '@haykay,', 'genomics,' 'Python,' , 'yinkadisa@gmail.com')
print("Grace Ajayi" , "gracejeta08@gmail.com" , "python" , "drug development" , "@grace")
# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jCse-gVO6Z7vO--dwYopHfftSflgJTbk
"""

#personal information
def personal_details():
    Name='Isa Joseph Danladi'
    Email='isahjoseph2014@gmail.com'
    Biostack='Genomics'
    Slack_username='@isa'
    print('Name:{}\n Email:{}\n Biostack:{}\n Slack_username:{}'.format(Name,Email,Biostack,Slack_username))
personal_details()print('TEAM-WATSON HACKBIO 2020 STAGE-0 TASK', end='\n *')
print('NAME:                   Peter Josiah Aminu', end='\n *')
print('EMAIL:                  josiahpeter61@gmail.com', end='\n *')
print('LANGUAGE:               Python', end='\n *')
print('BIOSTACK:               Genomics', end='\n *')
print('SLACK USERNAME:         @Josiah24')print('peter josiah aminu,', 'josiahpeter61@gmail.com,', 'python,', 'genomics,', '@josiah24')# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UuOnPAxdK8t5yuosbiulyExNhzypPcZE
"""

print('ejeh jemimah omaye,', '@omaye,', 'Python,' , 'jemimahomaye@gmail.com')# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a4j_tdRK_llmqF6KUcIXK-TwMMPq-rrj
"""

#HackBio Task1 REKHA BOHRA


print("My name is Rekha Bohra")
print("My email address is 19rekhabohra@gmail.com")
print ("The language I use is Python")
print ("My Biostack is Genomics and Drug designing")
print ("My slack user name is @rekbohr")name = ("Yusuf Faad Mayowa")
email = ("yusuffaad@gmail.com")
language = ("Python")
biostack = ("Data Analytics")
stackname = ("@faad")
print("Name: {}\nEmail: {}\nLanguage: {}\nBiostack: {}\nStackname: {}".format(name, email, language, biostack, stackname))
name = 'adeoye olude'
email = 'adeoyeifeoluwa@ymail.com'
language = 'python'
biostack = 'data Analysis'
slack_username = '@adeoye'
print ('adeoye olude', '@adeoye', 'python', 'data analysis','adeoyeifeoluwa@ymail.com')
# -*- coding: utf-8 -*-
"""Shekoni_task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nnQJglZESC6HAxTlfNstcBVhJau10lhZ
"""

print ("Name: Shekoni Olaitan Comfort")
print ("Email: shekoniolaitan77@gmail.com")
print ("Language: Python")
print ("Biostack: Genomics")
print ("Slack_Username: Hollainphinity")# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8akw0sVUPb0VzT4wJc7D6XkHsf1eJi7
"""

Name="Adisa Abdulhakeem Yinka"
Email_address="yinkadisa@gmail.com"
Language="Python"
Biostack="Genomics"
Slack_username="@Haykay"
print("Name:%s\n Email_address:%s\n Language:%s\n Biostack:%s\n Slack_username:%s"%(Name,Email_address,Language,Biostack,Slack_username))# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11B2dFA5UhrfC-BB8-nh8Nx70RccC2hOA
"""





"""Name = My name is Iqbal Hossain Nafiz
Email = My email address is nafiz.iqbal27cu@gmail.com
Language = python
Biostack = Vaccine Informatics
Slack username = Nafiz
"""

print ("My name is Iqbal Hossain Nafiz")
print ("My email address is nafiz.iqbal27cu@gmail.com")
print ("The language I used Python")
print ("My Biostack name is Vaccine Informatics")
print ("My Slack user name is Nafiz ")
# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LK3qc09qzDW4OXApeBuWf2JAff3NJYc0
"""

print ("my name is wasiu")
print ("my email address is wasiuabibu@yahoo.com")
print ("The language I used is python")
print ("my biostack is genomics and data analytics")
print ("my slack username is Abibu")
#!/usr/bin/env python
# coding: utf-8

# In[21]:

print('Ibitoye Opeyemi Isaac,', '@Highzhikk,', 'Python,' , 'Ibitoyeopeyemiisaac@gmail.com', 'Genomics')

# -*- coding: utf-8 -*-
"""HackBioikadan1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10uJLvXgYYbaVvbFBjns_jPDa9cghqnd5
"""

Name = "Ika Danjuma Mbateudi"
Email = "ikadanjuma@gmail.com"
Language = "python"
Biostack = "Drug development"
Slack_username = "@ikadan"
print('Ika Danjuma Mbateudi,', '@ikadan,', 'Python,' , 'ikadanjuma@gmail.com', 'Drugs development')
# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R70BYynqLJtr48NLscdnay5CCky3rTGN
"""

Name = "Shahana Malik"
Email-address = "shanimalik@aup.edu.pk"
Language = "Python"
Biostack = "Genomics"
Slack_username = "@shani"

print("My name is Shahana Malik") 
print("My email is shanimalik@aup.edu.pk")
print("My language is python")
print("My Biostack is Genomics ")
print("My slack username is @shani")
print('adisa abdulhakeem,', '@haykay,', 'genomics,' 'Python,' , 'yinkadisa@gmail.com')
print("Grace Ajayi" , "gracejeta08@gmail.com" , "python" , "drug development" , "@grace")
# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jCse-gVO6Z7vO--dwYopHfftSflgJTbk
"""

#personal information
def personal_details():
    Name='Isa Joseph Danladi'
    Email='isahjoseph2014@gmail.com'
    Biostack='Genomics'
    Slack_username='@isa'
    print('Name:{}\n Email:{}\n Biostack:{}\n Slack_username:{}'.format(Name,Email,Biostack,Slack_username))
personal_details()print('TEAM-WATSON HACKBIO 2020 STAGE-0 TASK', end='\n *')
print('NAME:                   Peter Josiah Aminu', end='\n *')
print('EMAIL:                  josiahpeter61@gmail.com', end='\n *')
print('LANGUAGE:               Python', end='\n *')
print('BIOSTACK:               Genomics', end='\n *')
print('SLACK USERNAME:         @Josiah24')print('peter josiah aminu,', 'josiahpeter61@gmail.com,', 'python,', 'genomics,', '@josiah24')# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UuOnPAxdK8t5yuosbiulyExNhzypPcZE
"""

print('ejeh jemimah omaye,', '@omaye,', 'Python,' , 'jemimahomaye@gmail.com')# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a4j_tdRK_llmqF6KUcIXK-TwMMPq-rrj
"""

#HackBio Task1 REKHA BOHRA


print("My name is Rekha Bohra")
print("My email address is 19rekhabohra@gmail.com")
print ("The language I use is Python")
print ("My Biostack is Genomics and Drug designing")
print ("My slack user name is @rekbohr")name = ("Yusuf Faad Mayowa")
email = ("yusuffaad@gmail.com")
language = ("Python")
biostack = ("Data Analytics")
stackname = ("@faad")
print("Name: {}\nEmail: {}\nLanguage: {}\nBiostack: {}\nStackname: {}".format(name, email, language, biostack, stackname))
name = 'adeoye olude'
email = 'adeoyeifeoluwa@ymail.com'
language = 'python'
biostack = 'data Analysis'
slack_username = '@adeoye'
print ('adeoye olude', '@adeoye', 'python', 'data analysis','adeoyeifeoluwa@ymail.com')
# -*- coding: utf-8 -*-
"""Shekoni_task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nnQJglZESC6HAxTlfNstcBVhJau10lhZ
"""

print ("Name: Shekoni Olaitan Comfort")
print ("Email: shekoniolaitan77@gmail.com")
print ("Language: Python")
print ("Biostack: Genomics")
print ("Slack_Username: Hollainphinity")# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8akw0sVUPb0VzT4wJc7D6XkHsf1eJi7
"""

Name="Adisa Abdulhakeem Yinka"
Email_address="yinkadisa@gmail.com"
Language="Python"
Biostack="Genomics"
Slack_username="@Haykay"
print("Name:%s\n Email_address:%s\n Language:%s\n Biostack:%s\n Slack_username:%s"%(Name,Email_address,Language,Biostack,Slack_username))# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11B2dFA5UhrfC-BB8-nh8Nx70RccC2hOA
"""





"""Name = My name is Iqbal Hossain Nafiz
Email = My email address is nafiz.iqbal27cu@gmail.com
Language = python
Biostack = Vaccine Informatics
Slack username = Nafiz
"""

print ("My name is Iqbal Hossain Nafiz")
print ("My email address is nafiz.iqbal27cu@gmail.com")
print ("The language I used Python")
print ("My Biostack name is Vaccine Informatics")
print ("My Slack user name is Nafiz ")
# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LK3qc09qzDW4OXApeBuWf2JAff3NJYc0
"""

print ("my name is wasiu")
print ("my email address is wasiuabibu@yahoo.com")
print ("The language I used is python")
print ("my biostack is genomics and data analytics")
print ("my slack username is Abibu")
